spring:
  application:
    name: ELK-STACK-EXAMPLE

server:
  port: 9898

logging:
  level:
    org:
      springframework:
        web: Error
    in:
      arifalimondal:
        crawlingservice: DEBUG

  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: D:/logs/elk-stack.log

