spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        encrypt:
          # We will send encrypted properties
          enabled: false
        git:
          uri: https://github.com/arifgit12/microservices-config-server.git
          searchPaths: report-service
          #defaultLabel: master
          #clone-on-start: true
server:
  port: 8888

